### ISSUE TITLE
SELinux issue with execmod on armv7hl

### ISSUE THREAD

**Issue by kwizart** [NVIDIA/libglvnd#116]
This issue was initially reported as https://bugzilla.redhat.com/1419944

There is a SELinux denial because libGLdispatch.so.0.0.0 try to use execmod
This was reproduced on armv7hl and not reproduced on x86_64.
(probably not yet tested on i686 , ppc64, ppc64le, aarch64)

SELinux is preventing gdm-wayland-ses from execmod access on the file /usr/lib/libGLdispatch.so.0.0.0.

```
*****  Plugin allow_execmod (91.4 confidence) suggests   *********************

If you want to allow gdm-wayland-ses to have execmod access on the libGLdispatch.so.0.0.0 file
Then you need to change the label on '/usr/lib/libGLdispatch.so.0.0.0'
Do
# semanage fcontext -a -t textrel_shlib_t '/usr/lib/libGLdispatch.so.0.0.0'
# restorecon -v '/usr/lib/libGLdispatch.so.0.0.0'

*****  Plugin catchall (9.59 confidence) suggests   **************************

If you believe that gdm-wayland-ses should be allowed execmod access on the libGLdispatch.so.0.0.0 file by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'gdm-wayland-ses' --raw | audit2allow -M my-gdmwaylandses
# semodule -X 300 -i my-gdmwaylandses.pp
```

Here is the link for execmod issue from Daniel Walsh.
http://danwalsh.livejournal.com/6117.html

**Comment by kbrenneman** [comment]
Ah, the problem is that the assembly code for ARMv7 doesn't go through the GOT or PLT when it looks up _glapi_Current and _glapi_get_current, so the loader has to relocate it.

It's basically the same problem as #108, except that I don't know ARMv7 well enough to know how to fix it.

As a partial workaround, you could use --disable-asm to make it just use the C stubs. That'll avoid the TEXTREL problem, but it would also prevent libglvnd from being able to generate dispatch stubs for any new extension functions.

**Comment by kbrenneman** [comment]
Another possibility is that I think I could rearrange things so that it'll use C code for the static dispatch stubs, but still be able to generate new assembly stubs at runtime.

The generated stubs don't have to worry about the GOT or PLT, since we can just figure out the necessary addresses for everything at runtime and plug them in.

What we'd lose there is the ability for a vendor library to patch the static dispatch stubs. But at the moment, I don't think any driver actually does that on ARM.

**Comment by kbrenneman** [comment]
The TSD assembly stubs in GLVND are the problem -- they're not written as position independent code, so the loader has to relocate them. We don't have TLS stubs for ARMv7 at all yet.

If you disabled assembly entirely when building libglvnd, then it would instead use dispatch stubs written in C. Those can use either TLS or TSD, but in both cases, the compiler will produce position independent code, so it won't have this problem. At that point, you might as well use TLS because it's faster.

All of the above only applies to libglvnd's dispatch stubs. While libglvnd's dispatching is based on Mesa's, neither one cares about how the other is implemented. One of libglvnd's basic requirements is that it has to be able to forward calls to any driver and not care how the driver dispatches those calls internally.

That said, I don't think Mesa has ARMv7 assembly support at all, so it would be using C for its dispatch stubs as well.
