### ISSUE TITLE
[RFE] Configurable page size on aarch64

### ISSUE THREAD

**Issue by kwizart** [NVIDIA/libglvnd#132]
Fedora kernel uses a CONFIG_ARM64_4K_PAGES=y by default
Since commit cfce0c8 the default is now 64K, so I wonder if it would be better to make a configure option instead ?

**Comment by kbrenneman** [comment]
It would be better, and I made sure to set it up so that you could override it from the configure script. I just haven't gotten a chance to implement that yet.

Basically, the configure script just needs to get the value of sysconf(_SC_PAGESIZE), then plug that into an AC_DEFINE.

**Comment by aaronp24** [comment]
What happens if a binary built on one kernel runs on one with a different page size? Can this be handled at runtime or would that be bad for performance?

**Comment by kbrenneman** [comment]
At that point, you'd lose the entrypoint patching functionality, because it wouldn't be able to call mprotect on the statically defined dispatch stubs.

The performance impact from that depends on whether a vendor library actually uses entrypoint patching, and how much a given application would benefit from it.

As far as I know, though, no existing driver uses entrypoint patching for aarch64.
