### ISSUE TITLE
'undefined symbol'  for some OpenGL ES 3.x  funcs 

### ISSUE THREAD

**Issue by canatan** [NVIDIA/libglvnd#134]
Thank you for providing libglvnd. i discover something.

if libGLESv2.so is about to support both OpenGL ES 3.x and 2.x  why below so:

`sh-4.4$ readelf -s --wide /usr/lib/libGLESv2.so.2.0.0 | grep glResumeTransformFeedback
    51: 00000000000084c0     0 FUNC    GLOBAL DEFAULT   13 glResumeTransformFeedback
`
`
#sh-4.4$ readelf -s --wide /usr/lib/libGLESv2.so.2.0.0 | grep glMemoryBarrier
`
`
sh-4.4$ pacman -Qo /usr/lib/libGLESv2.so.2.0.0 
/usr/lib/libGLESv2.so.2.0.0 is owned by libglvnd 0.2.999+g4ba53457-2
`
`
sh-4.4$ 
`
i get  'undefined symbol'  when linking with -lGLESv2
do we have to use eglgetprocaddress for them?
when i link with -lOpenGL  instead of -lGLESv2   app.  build and successfully. is this by luck?
is this legal that  link with -lOpenGL  instead of -lGLESv2 for an ES application?

Additionally when i remove the 'glMemoryBarrier' in C source but left  'memoryBarrier'
shader built-in as is in shader source program build successfully but not run. 
Shaders print 'undefined  xxx'  where  xxx is  some  random  weird characters.

TIP : glResumeTransformFeedback  introduced with 3.x

Kabylake GPU and mesa-17.1.8  here.

**Comment by kbrenneman** [comment]
There was a typo that caused the GLES library to be missing the GLES 3.1 and 3.2 symbols, one of which is glMemoryBarrier. That was fixed in #131.

@canatan - Can you test the current master version of libglvnd?

Also, if you need a program to work with a version of libglvnd without that fix, then calling eglGetProcAddress will work.

**Comment by canatan** [comment]
hey. Thank you for quick fix. I will check and return feedback as soon as possible.

BTW: How about your 'make check'  target  checking for missing symbols.

**Comment by canatan** [comment]
i build master tested against it. i confirm that the fix worked.  thank you for quick fix

**Comment by kbrenneman** [comment]
Closing.

Adding a unit test for this sort of thing has come up before, but such a test would run into the same problem. To write that test, you'd need a known-correct list of the symbols that you expect to find. But, the underlying problem is that we didn't have a correct list of symbols. That is, if you can write a correct test, then you don't need the test.
