### ISSUE TITLE
tests fail on several architectures

### ISSUE THREAD

**Issue by tjaalton** [NVIDIA/libglvnd#154]
I enabled tests on the Debian package (based on f6d236e8dc8efbd) and noticed that the tests fail on most architectures, like so:

make[6]: Entering directory '/<<BUILDDIR>>/libglvnd-1.0.0+git20180308/build/tests'
PASS: testgldispatch_static.sh
FAIL: testgldispatch_generated.sh
FAIL: testgldispatch_patched.sh
PASS: testglxcreatecontext.sh
FAIL: testglxmcbasic.sh
FAIL: testglxmcloop.sh
FAIL: testglxmcthreads.sh
FAIL: testglxmclate.sh
FAIL: testglxmcoldlink.sh
FAIL: testglxgetprocaddress.sh
FAIL: testglxgetprocaddress_genentry.sh
PASS: testglxgetclientstr.sh
PASS: testglxqueryversion.sh
FAIL: testpatchentrypoints.sh
PASS: testegldisplay.sh
PASS: testegldevice.sh
PASS: testeglgetprocaddress.sh
PASS: testeglmakecurrent.sh
PASS: testeglerror.sh
PASS: testegldebug.sh
============================================================================
Testsuite summary for libglvnd 1.0.0
============================================================================
# TOTAL: 20
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  10
# XPASS: 0
# ERROR: 0

failing architectures are; armel, armhf, mips, mips64el, mipsel, s390x and a bunch of others that aren't supported. The tests pass on amd64, arm64, i386, ppc64el.

**Comment by nwnk** [comment]
On the arches that fail, you're hitting the pure C dispatch path. Said path does not implement the full insanity of `glXGetProcAddress`, in particular `glXGetProcAddress("glHamSandwich")` will not jit a stub function. The tests that fail depend on that working.

In practice this isn't a huge issue. glvnd has static stubs for pretty much everything in the GL registry (though the XML hasn't been updated in quite a while), so any _real_ use of `GetProcAddress` will work as expected. If you were writing a new GL extension with new entrypoints, and decided to do so on one of the pure-C architectures, your life would be difficult, and you'd want to rebuild glvnd with your extension added to the XML; the set of people having that problem is quite small, I imagine.

**Comment by kbrenneman** [comment]
We've migrated the repository over to GitLab, so this is now tracked at https://gitlab.freedesktop.org/glvnd/libglvnd/issues/154.
