### ISSUE TITLE
libglvnd xorg 1.20 support?

### ISSUE THREAD

**Issue by randyrandersn** [NVIDIA/libglvnd#155]
Is this coming any time soon for the 390.xx / 396.xx linux drivers?

**Comment by kbrenneman** [comment]
Libglvnd is the client-side libraries. As long as the server exposes the GLX extension, that's all that libglvnd needs.

**Comment by aaronp24** [comment]
We're working on it, but support wasn't quite ready for the 396 release. It should show up in a future release, but I'm not sure yet which release branch that's going to be. We're probably not going to backport it to release 390 or older, though.

Since this is an NVIDIA driver issue and not directly libglvnd's fault, closing this issue.
