### ISSUE TITLE
eglGetCurrentContext returns destroyed context

### ISSUE THREAD

**Issue by Josua-SR** [NVIDIA/libglvnd#166]
Hi there;

While prototyping a vendor implementation for the Vivante EGL binaries I noticed a difference in behaviour to both Mesa(Intel gpu) and the NVIDIA binaries:
```
eglCreateContext
eglDestroyContext
eglCreateContext
```
^^ The second call to eglCreateContext may return an identical address to the first call.
This confuses glvnd in such a way that the following chain fails to dispatch the second call of eglMakeCurrent to the vendor library:
```
eglCreateContext
eglMakeCurrent
eglDestroyContext
eglCreateContext
eglMakeCurrent <-- this one actually never happens
```

This in turn makes OpenGL-ES (we only work on gles at this time) calls stop working.

So why this title to the issue?
While writing a testcase I noticed that glvnd does not dispatch calls to eglGetCurrentContext to the vendor library.
Instead it returns the last known context, even if it has already been destroyed by eglDestroyContext.

So another sample:
```
ctx = eglCreateContext()
eglMakeCurrent(ctx)
eglDestroyContext(ctx)
eglGetCurrentContext()
```

The Vivante libEGL returns EGL_NO_CONTEXT here as one would expect, but glvnd returns the now invalid handle on the previous context.
I believe this is the heart of the problem.

As a work-around I have patched the test application glmark2 to call
```eglMakeCurrent(display, EGL_NO_SURFACE, EFL_NO_SURFACE, EGL_NO_CONTEXT)```
right after eglDestroyContext.

And this tiny change makes all the difference between glGetString returning 0, and glmark2 running through all the way.

I believe this should be fixed by catching calls to eglDestroyContext to update the currentContext state in glvnd.

**Comment by kbrenneman** [comment]
Libglvnd's behavior is correct. If a context is current, then eglDestroyContext or eglTerminate will mark the context for deletion but will not destroy them until they are no longer current. Likewise, calling eglDestroyContext does not change the return value of eglGetCurrentContext.

The same is true of EGLSurface handles -- eglDestroySurface will mark them for deletion, but they stick around until they're no longer current.

Also remember that a context or surface could be destroyed on one thread while it's current on a different thread.


From the EGL 1.5 spec, section 3.2:

> If contexts or surfaces, created with respect to dpy are current (see section 3.7.3) to any thread, then they are not actually destroyed while they remain current. If other resources created with respect to dpy are in use by any current context or surface, then they are also not destroyed until the corresponding context or surface is no longer current.

**Comment by Josua-SR** [comment]
> From the EGL 1.5 spec, section 3.2:
Oh!

Then I am not sure what to do.
Our problem is that after destroying a context and then creating a new one that happens to have an identical handle, the next call to eglMakeCurrent isn't being dispatched to the vendor library.

So we call eglDestroyContext.
That means the context should be marked for deletion, right?

Then a call of eglMakeCurrent for a different context should trigger the deletion at least for the current thread, right?

Any idea how we can communicate to glvnd that a context is a new context even though the handle happens to be identical to a previous context?
It is very important here that after eglCreateContext, the eglMakeCurrent call is dispatched to the vendor library.

**Comment by Josua-SR** [comment]
....

**Comment by Josua-SR** [comment]
Maybe I can be more precise here:

From the EGL 1.5 spec, section 3.7.2:
> Following eglDestroyContext, the context and the handle referring to it are treated in the same fashion as a context destroyed by eglTerminate (see section 3.2)

From the EGL 1.5 spec, section 3.2:
> Termination marks all EGL-specific resources, such as contexts and surfaces, associated with the specified display for deletion. Handles to all such resources are invalid as soon as eglTerminate returns,

This last part seems important to me: Handles are invalid as soon as eglDestroyContext returns.
Therefore also the handle stored state->currentContext is invalid at the same time.

**Comment by kbrenneman** [comment]
The problem is that eglCreateContext is returning an EGLContext handle that's still in use.

If you call eglDestroyContext on a current context (current to ANY thread, remember), then the context is marked for deletion, but it is not deleted. The context still exists, and the EGLContext handle still exists, even if it's not valid to pass to any other functions.

If eglCreateContext returns an EGLContext handle that's marked for deletion but not deleted, then that is a bug in the vendor library.

If you think about it, that's the only way to keep coherent behavior for all of the thread-local state in EGL, especially in an intermediate layer like libglvnd. If you call eglDestroyContext while another thread has that context current, then you can't update the other thread's state. As far as the other thread knows, that context is still current.

To give a more concrete example:

```C
EGLContext ctx1 = eglCreateContext(dpy, config, NULL, NULL);
eglMakeCurrent(dpy, surf, surf, ctx1);
eglDestroyContext(dpy, ctx1);
// ctx1 is only marked for deletion. It still exits and is still current.
assert(eglGetCurrentContext() == ctx1);

EGLContext ctx2 = eglCreateContext(dpy, config, NULL, NULL);
// ctx1 still exists, so eglCreateContext can't return the same handle as ctx1
assert(ctx2 != ctx1);

eglMakeCurrent(dpy, surf, surf, ctx2);
// Now, ctx1 is no longer current and is destroyed.

EGLContext ctx3 = eglCreateContext(dpy, config, NULL, NULL);
if (ctx1 == ctx3) {
    // This can happen. ctx1 was destroyed when it was no longer current, so
    // the vendor is allowed to re-use the handle.
    printf("Re-used context handle.\n");
}
```

In that code, neither of the asserts can fail, but the `if (ctx1 == ctx3)` branch at the end could happen.

**Comment by Josua-SR** [comment]
I get your point there, thank you!

My colleague found some ambiguity in section 3.7.4:
> If there is no current context for the current rendering API, or if the current rendering API is EGL_NONE, then EGL_NO_CONTEXT is returned (this is not an error). If the current context has been marked for deletion as a result of calling eglTerminate or eglDestroyContext, the handle returned by eglGetCurrentContext is not valid, and cannot be passed successfully to any other EGL function, as discussed in section 3.2.

I find this paragraph quite unreadable. So if a context marked for deletion is still current, getCurrentContext may return something, anything I guess, and it is not valid.

Nevertheless the problem of the return value of getCurrentContext remains.
The specification says that once eglMakeCurrent is called (I add here in my mind: with any handle whatsoever even if it looks like a known handle) the previous context handle isn't valid at this point for the current thread. Therefore it should nto be used, not even to compare to.

I drafted a patch explaining this:
```
From e0c6d6ea79b390c3e4ba3738a37b6d50cea87f4d Mon Sep 17 00:00:00 2001
From: Josua Mayer <josua@solid-run.com>
Date: Tue, 9 Oct 2018 20:47:31 +0200
Subject: [PATCH] avoid short-cut in eglMakeCurrent

A Context or surface may have been marked for deletion in the past and
is invalidated by calls to either eglMakeCurrent or eglReleaseThread.
Even if the handle of the new context looks identical it can be
different. Therefore eglMakeCurrent must be dispatched to the vendor library.

Signed-off-by: Josua Mayer <josua@solid-run.com>
---
 src/EGL/libegl.c | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/src/EGL/libegl.c b/src/EGL/libegl.c
index 54e3a28..2fb4390 100644
--- a/src/EGL/libegl.c
+++ b/src/EGL/libegl.c
@@ -692,8 +692,10 @@ PUBLIC EGLBoolean EGLAPIENTRY eglMakeCurrent(EGLDisplay dpy,
         if (dpy == oldDpy->dpy && context == oldContext
                 && draw == oldDraw && read == oldRead) {
             // The current display, context, and drawables are the same, so just
-            // return.
-            return EGL_TRUE;
+            // return, unless the context or a surface has been marked for deletion by 
+            // eglDestroyContext or eglDestroySurface!
+            // Because we currently do not remember if a handle has been marked, we can't take this short-cut. 
+            // return EGL_TRUE;
         }
     } else {
         // We don't have a current context already.
-- 
2.19.0
```

**Comment by kbrenneman** [comment]
The "If the current context has been marked for deletion..." means that if you've called eglDestroyContext on the current context, then eglGetCurrentContext still returns the same context handle.

Again, the problem here is not in eglGetCurrentContext. The problem is that your implementation of eglCreateContext needs to return a different handle value.

**Comment by cubanismo** [comment]
> Again, the problem here is not in eglGetCurrentContext. The problem is that your implementation of eglCreateContext needs to return a different handle value.

To be fair, I don't think the EGL spec requires this, given the quoted portions above.  However, I can imagine GLVND requires it to reasonably implement its dispatching.  GLVND has various minor requirements like this above & beyond what EGL and GLX themselves require.

**Comment by Josua-SR** [comment]
I have the impression that glvnd takes two unnecessary short-cuts here.
1) never call the vendor implementation of eglGetCurrentContext
2) not dispatch an actual call of eglMakeCurrent to the vendor implementation

I think removing the second short-cut has no negative side-effects.
Maybe it should leave the decision if a context is current up to the vendor implementation.

**Comment by kbrenneman** [comment]
Libglvnd makes the assumption that when a context is current, it stays current until a call to eglMakeCurrent or eglReleaseThread. It also assumes that an EGLContext handle corresponds to exactly one context, and corresponds to the same context for as long as that context exists.

Even if that second assumption isn't a hard requirement from the spec, you can treat it as a requirement for the libglvnd interface to be able to function, just like requiring that EGLDisplay handles have to be pointers.

**Comment by jnettlet** [comment]
I believe the problem with those assumptions is that libglvnd, as you stated earlier, is an intermediate layer.  Therefore making it adhere to a more restrictive interpretation of the spec than the underlying drivers is going to limit its usefulness.  This may be fine for nvidia who is working lock step with the interpreted standard as implemented, or the standard is implemented to how nvidia perceives it.  But overall the utility of libglvnd for OSS to integrate other binary drivers will be diminished since they generally are stuck implementing around binary drivers as they exist, rather than how libglvnd expects them to be.  I think in the event of situations like this it would most likely be best to punt to the actual backend rather than trying to fastpath in libglvnd.

**Comment by kbrenneman** [comment]
In most cases, I'd agree, and in fact, I've done my best to keep the assumptions and added requirements to a minimum.

In this case, though, the assumption that context handles don't change out from under it is required for libglvnd to keep track of the current context (as well as the current display, drawables, and vendor).

The fact that libglvnd keeps track of the current context, in turn, is already explicitly defined as part of the vendor library interface. It can't punt that to a vendor library, because the vendor library is already allowed to punt that back to libglvnd.

Conversely, just not re-using an EGLContext handle for a context that still exists should be fairly easy for a vendor library.

**Comment by jnettlet** [comment]
I would like to come up with a solution to this that covers the spec as completely as possible.  I have been looking over the code, and the EGL 1.5 spec some more and I believe even more firmly that the spec isn't ambiguous and that after eglDestroyContext is called, that pointer is no longer valid.  If you read the highlighted Error note under eglGetCurrentSurface,  

`Errors
eglGetCurrentContext (I believe this is a type and means eglGetCurrent Surface) returns EGL_NO_SURFACE on failure (but may
also return it if no context is bound, as described above)`

The if no context is bound is referring to if eglGetCurrentContext is called after eglDestroyContext or eglTerminate.   I think that re-emphasises that the implementation within the Vivante binaries is not against the spec, but just their interpretation of the implementation.

Understanding that it is libglvnd's purpose to manage the state of the Context, I would like to suggest that we allow the vendor glvnd library provide a flag dictating if it follows this implementation.  If this flag is set then libglvnd will do 2 things differently internally.

1)  It will not use the cached context when eglGetCurrentContext() is called, instead punting out to the binary
2)  Will not fast path the eglMakeCurrent call if oldContext == context.

This will not effect the current exposed API, nor functionality if this is not set.

Another route would be to make eglDestroyContext() and eglTerminate() functions that are exported through libglvnd like eglGetCurrentContext, and they are normally passed through to the binaries as expected.  If the flag is set specifying the vendor binary invalidates the Context after being destroyed then libglvnd updates the state accordingly by calling out to the vendors eglGetCurrentContext.

We already have some internal patches that implement this and it does fix the issues we are running into.

**Comment by kbrenneman** [comment]
Better coverage of the spec is all well and good, but not at the cost of having to keep two different paths for current context management.

Can you please explain what's preventing you from changing the handle value in your driver?

**Comment by jnettlet** [comment]
We are simple writing an OSS glvnd implementation for an existing binary driver from Vivante provided by NXP.  We have no access to the source of the userspace drivers.

**Comment by Josua-SR** [comment]
> Better coverage of the spec is all well and good, but not at the cost of having to keep two different paths for current context management.

I get the point. We are a little boxed in here though: On the one hand we have glvnd manage current context and surfaces by design; On the other hand we found this internal state to be inaccurate with regards to this specific Vivante implementation.

Don't take next paragraph as final final please, it is definitely an unfinished train of thought:
Thinking about this for a while has led my brain down the extreme path of challenging the design decision of glvnd to keep track of what context and what surfaces are current; and hide real calls that an application makes from the vendor EGL (getCurrentContext and makeCurrent).
For one part this duplicates logic, since the vendor EGL must already keep track of these things;
further we have now found a particular implementation of EGL that behaves a little different from both Mesa and Nvidia.

**Comment by kbrenneman** [comment]
If you can't modify the original driver, does that mean you're writing a wrapper around an existing non-libglvnd libEGL.so implementation?

**Comment by jnettlet** [comment]
correct

**Comment by kbrenneman** [comment]
That does make things trickier. Libglvnd is largely designed with the expectation that a driver can be modified to match the added requirements of the libglvnd interface. From that standpoint, I'd expect the eglDeleteContext semantics to be one of the less onerous changes.

But, in a wrapper, you could still implement the same semantics by doing your own context and surface tracking.

**Comment by jnettlet** [comment]
We are already doing quite a bit in our wrapper in order to handle the way that the Vivante libraries are built.  The reason we were interested libglvnd was because the interface was already implemented in mesa and we were looking for easier integration into more distributions moving forward.  Currently all our initial testing is working quite well, with this case being the only real show stopper to move into more widespread testing.

The only reason we opened this bug was because these interfaces are strictly hidden inside of the core of libglvnd library.  If the APIs were exposed to be overridden in the vendor layer then it would not be a problem for us.  I guess if you are unwilling to come to a compromise we will need to either have the distributions pick up our patch, or just move forward with our own fork and present that to other groups who need more flexibility in integrating their binary drivers into the interface.

**Comment by kbrenneman** [comment]
Rewriting the current context tracking isn't a hard no, but adding two paths to deal with something that could be (and arguably should be) handled in the vendor library seems like a really bad design decision to me.

I'd only consider it if it's really impossible to handle that in the vendor library (driver or wrapper). It's hard for me to say anything more concrete than that without seeing the wrapper code, though.

Even if that does end up being the route to go, I'll need to go through the rest of libglvnd to make sure I'm not breaking anything else in the process, since it means changing some pretty basic assumptions. I don't know when I'd be able to get to something like that.

**Comment by mwelchuk** [comment]
@jnettlet Has this been published anywhere yet?

**Comment by jnettlet** [comment]
@mwelchuk Sorry we have not published the sources yet.  We are reworking our layer to also include support for the new AARCH64 binaries.  We do now have contact with Vivante so hopefully we can work together to provide a better solution than our hacks going forward.

**Comment by agners** [comment]
@jnettlet any update on this? Having libglvnd for Vivante drivers seems worthwhile.

**Comment by jnettlet** [comment]
@agners we are still working on the tooling, so it is more sustainable.  Because of the way vivante builds their binaries, and the license they have for not allowing modified binaries, we are having to do some backhanded techniques to get everything working seamlessly.  Internally some other projects took priority, but I think we will be getting back to this soon.

**Comment by jnettlet** [comment]
Is this clarification being made in the next version of the khronos spec,
or it is just something that NVidia has determined and is pushing as their
interpretation?

**Comment by jnettlet** [comment]
Can you link to the conversation that came to this decision so we can
have it on the record?

**Comment by kbrenneman** [comment]
I'm also kind of curious -- after you call eglDestroyContext with the current context, what does Vivante's driver return when you call eglGetCurrentSurface or eglGetCurrentDisplay? And what does it do if you have the context current to another thread?

Given that odd behavior of re-using a context handle, it's possible that they're actually doing an implicit eglMakeCurrent(NULL) when you call eglDestroyContext.

**Comment by kbrenneman** [comment]
We've migrated the repository over to GitLab, so this is now tracked at https://gitlab.freedesktop.org/glvnd/libglvnd/issues/166.
