### ISSUE TITLE
Investigate Python 2+3 support for generators

### ISSUE THREAD

**Issue by nanonyme** [NVIDIA/libglvnd#168]
Currently this package requires Python 2 to build from Git. Distributions are pushing for Python 2 to be removed from basic installations but currently this library has hard dependency on it.

This ticket is about investigating whether support for Python 3 can be added without reduction of maintainability

**Comment by kbrenneman** [comment]
Libglvnd already works with Python 2 or Python 3. The configure script will find whichever one is available, and then the code generation scripts will produce identical output in either case.

Also, the tarball that you get from "make dist" includes all of the generated files, and it's set up so that it will work if you don't have Python installed at all.

Do we still have Python 2 listed as a dependency somewhere?

**Comment by nanonyme** [comment]
Yes, you seemed to have Python 2 requirement in configure if not using release tarball

**Comment by nanonyme** [comment]
If this already works and it's just a leftover check, all the better

**Comment by kbrenneman** [comment]
Can you clarify what you found that's left over?

**Comment by nanonyme** [comment]
https://github.com/NVIDIA/libglvnd/blob/master/configure.ac#L31-L36 I'm referring to this piece of code. There's two branches, one of which mandates Python 2

**Comment by kbrenneman** [comment]
Ah, the AM_PATH_PYTHON macro takes a minimum version, but if you specify a Python 2 minimum version, then it'll also match Python 3.

**Comment by nanonyme** [comment]
Ah, sorry. Never mind. You just apparently haven't rolled a release with the code segment I was referring to is present
