### ISSUE TITLE
How to remove this package?

### ISSUE THREAD

**Issue by mehameha998** [NVIDIA/libglvnd#173]
Any one can explain the difference between libglvnd and egl?

**Comment by kbrenneman** [comment]
You should be able to install and remove the libglvnd files with "make install" and "make uninstall", respectively.

Generally, though, you'll want to just use your distro's package manager: If your distro offers a libglvnd package, then use the package manager to install or remove it. If your distro doesn't offer a libglvnd package, then libglvnd probably won't be useful to you anyway because other packages won't be built to use it.

As for libglvnd versus EGL: EGL is an interface that a program uses to talk to a graphics driver. Libglvnd lets multiple drivers coexist on the same system without clobbering each other, and makes sure that a program talks to the correct driver.
