### ISSUE TITLE
How to load a specific version of GLX for software rendering?

### ISSUE THREAD

**Issue by edahlgren** [NVIDIA/libglvnd#177]
I'd like to use software rendering via mesa's swrast_dri.so, even though I have nvidia drivers installed on my system. Is this possible?

My guess is that it is, but whenever I strace glxinfo (linking with libglvnd's libGL.so.1), I only see libGLX_nvidia.so.0 being searched, even if I put mesa in my LIBGL_DRIVERS_PATH (eventually fails on no libGLX_indirect). 

I assume this is because my host X server is telling libglvnd that nvidia drivers should be used exclusively? Can I bypass this, since for software rendering I don't actually care about the direct rendering drivers on my host?

**Comment by kbrenneman** [comment]
When you make the first GLX function call for a particular display and screen number, libGLX.so (and by extension, libGL.so) will try to query the server to ask it which vendor library to use. The server reply based on which server-side GLX module is loaded. Thus, libglvnd will try to pick whichever client-side driver matches the server.

If the server doesn't send back a vendor name, or sends back a vendor that the client can't load, then it'll fall back to using libGLX_indirect.so.0, which is be a symlink to another vendor library.

You can tell it to load a specific vendor library by setting the environment variable __GLX_VENDOR_LIBRARY_NAME. If you want to force it to use Mesa (libGLX_mesa.so.0), then you'd do this:
```
__GLX_VENDOR_LIBRARY_NAME=mesa glxgears
```

Note that for that to work, you need a version of Mesa that's built to use libglvnd. If your distro doesn't provide one, then you might need to build it yourself.

**Comment by edahlgren** [comment]
@kbrenneman Thanks! Give me a day to test/confirm (a little busy atm), and I'll close this issue out.

**Comment by jrmuizel** [comment]
I get the following error when running  `__GLX_VENDOR_LIBRARY_NAME=mesa glxgears`
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  39
  Current serial number in output stream:  38
```

**Comment by kbrenneman** [comment]
That tells you that libglvnd loaded Mesa like you wanted it to, but Mesa can't load the swrast driver. You've got some problem in how you've installed or configured Mesa, but just from that error message, I can't make any guesses as to what.

**Comment by aaronp24** [comment]
I wonder if `libglxserver_nvidia` is sending fbconfig attributes that Mesa doesn't understand, preventing it from picking one. Someone will have to step through Mesa's fbconfig selection code to see why it doesn't like any of the fbconfigs we're providing.

**Comment by kbrenneman** [comment]
That's possible. Mesa will ignore any visual/fbconfig attributes that it doesn't recognize, but I think it has to map whatever it gets from the server to something from the swrast driver. If it can't find any matches, then I think it'll end up with an empty visual and fbconfig list.

I agree that you'd need to run a debugger to see what it's actually running into. Whatever the problem is, though, it's not related to libglvnd.

**Comment by nwnk** [comment]
> Mesa will ignore any visual/fbconfig attributes that it doesn't recognize, but I think it has to map whatever it gets from the server to something from the swrast driver. If it can't find any matches, then I think it'll end up with an empty visual and fbconfig list.

This is, sadly, the case. It's a source of bugs even for trying to use a software renderer against a screen that Mesa would otherwise have a hardware driver for. In effect the software driver loader simply fabricates a list of fbconfigs and then tries incompetently to find a sufficiently compatible config from the real glx config list. (This is an artifact of attempting to support a software driver against an X server with no actual GLX extension, which at this point is maybe not a configuration worth caring so much about.)

I think this issue can be closed, it's certainly nothing to do with glvnd.
