### ISSUE TITLE
eglQueryDevicesEXT not work

### ISSUE THREAD

**Issue by joshuafc** [NVIDIA/libglvnd#196]
Ubuntu system, nvidia driver(install by run file) not provide OpenGL headers, so get headers from this project. found this project can build a libEGL.so. Then just make a try, and found:

- eglQueryDevicesEXT can get address but always report there are `0` device.
- eglQueryDeviceAttribEXT even cannot get address.

if use libEGL provide by driver, above codes will works. 
```
// Get EGL API Function Pointer
PFNEGLQUERYDEVICESEXTPROC eglQueryDevicesEXT =
        (PFNEGLQUERYDEVICESEXTPROC)
                eglGetProcAddress("eglQueryDevicesEXT");

PFNEGLQUERYDEVICEATTRIBEXTPROC eglQueryDeviceAttribEXT =
        (PFNEGLQUERYDEVICEATTRIBEXTPROC)
                eglGetProcAddress("eglQueryDeviceAttribEXT");

static const int MAX_DEVICES = 16;
EGLDeviceEXT eglDevs[MAX_DEVICES] = {0};
int cudaDeviceNum = 0;
EGLint eglDeviceNum = 0;
CHECK_EQ(cuDeviceGetCount(&cudaDeviceNum), CUDA_SUCCESS);
CHECK_EQ(eglQueryDevicesEXT(MAX_DEVICES, eglDevs, &eglDeviceNum), EGL_TRUE) << "EGL Get Devices Failed!";
CHECK_EQ(cudaDeviceNum, eglDeviceNum) << "EGL Device Number != CUDA Device Number !!!";
```

```
Sat Feb 15 18:53:16 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   42C    P8    28W / 260W |    552MiB / 11016MiB |     15%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1842      G   /usr/lib/xorg/Xorg                           311MiB |
|    0      7175      G   /opt/teamviewer/tv_bin/TeamViewer             24MiB |
|    0      7508      G   compiz                                       147MiB |
|    0      9685      G   ...AAAAAAAAAAAAAAgAAAAAAAAA --shared-files    34MiB |
|    0     26430      G   ...e/SoftFiles/clion-2019.2.4/jbr/bin/java     8MiB |
+-----------------------------------------------------------------------------+

```

What is the different between libEGL.so from this project and from drivers 440. Is user can use this project instead of link shared libraries from drivers by design?

**Comment by kbrenneman** [comment]
The libEGL.so library from libglvnd isn't a driver, it's a library that loads a driver. The application links against libEGL.so, libEGL.so finds and loads whatever drivers you have installed, and then the drivers actually implement the various EGL and OpenGL functions.

Each driver provides a library with a name like libEGL_nvidia.so, so that you can install multiple drivers and they won't overwrite each other. The libglvnd readme file has more details about how libEGL.so finds and loads drivers:
https://gitlab.freedesktop.org/glvnd/libglvnd/blob/master/README.md#egl-dispatching

When you call eglQueryDeviceEXT, then libEGL.so will forward that call to each driver (libEGL_nvidia.so, libEGL_mesa.so, etc). Each driver returns EGLDeviceEXT handles for any devices that it supports, and then libEGL.so will return those handles back to the caller.

Without a driver, there's nothing that can find or talk to any devices.

Also, if you don't have a driver installed, then the extension string from `eglQueryString(EGL_NO_DISPLAY, EGL_EXTENSIONS)` won't list `EGL_EXT_device_enumeration`, so you shouldn't be calling eglQueryDeviceEXT in the first place.

**Comment by joshuafc** [comment]
@kbrenneman But I already installed driver by `NVIDIA-Linux-x86_64-440.44.run`.  And there is a file `/usr/share/glvnd/egl_vendor.d/10_nvidia.json` with content :
```
{
    "file_format_version" : "1.0.0",
    "ICD" : {
        "library_path" : "libEGL_nvidia.so.0"
    }
}
```
eglQueryDeviceEXT still not report any device.

**Comment by kbrenneman** [comment]
If `eglGetProcAddress("eglQueryDeviceAttribEXT")` returns NULL, then that suggests that libglvnd either didn't find the JSON file, or that it can't load libEGL_nvidia.so.0 for some reason.

Did you build libglvnd yourself, or are is it from your package manager? If you built libglvnd yourself, then you might need to put the JSON files somewhere else, depending on what configure options you used.

If libglvnd can find the JSON file, but can't find libEGL_nvidia.so.0, then you can set LD_DEBUG to find out where it's looking for libraries, like this:
```LD_DEBUG=libs es2gears```
