### ISSUE TITLE
[Minor thing] Release tarball with full URL?

### ISSUE THREAD

**Issue by rubyFeedback** [NVIDIA/libglvnd#212]
Hey folks,

The old 1.2.0 release is available at:

    https://github.com/NVIDIA/libglvnd/releases/download/v1.2.0/libglvnd-1.2.0.tar.gz

I like that URL; simple to wget.

The new release is available at:

    https://github.com/NVIDIA/libglvnd/archive/refs/tags/v1.3.4.tar.gz

Now ... this is a minor thing. I can wget this fine and extract it via scripts
anyway, and then compile it. But my scripts work better with URL schemes
such as for the 1.2.0 release of libglvnd.

If it is not too much work, could the URL:

        https://github.com/NVIDIA/libglvnd/releases/download/v1.3.4/libglvnd-1.3.4.tar.gz

also be added?

Sorry for nitpicking, it is just easier to deal with consistent URL schemes for my scripts
and there were libglvnd releases that had that schemata in use, so not sure why it is
not the same now making me a sad panda (although, yes, it's so minor ... not even
sure whether to report it or not, but either way please feel free to close this issue
at any moment in time!).

**Comment by kbrenneman** [comment]
Libglvnd is hosted on GitLab now, not GitHub, so that's where new releases are:
https://gitlab.freedesktop.org/glvnd/libglvnd/-/releases

The more recent tarballs without the `libglvnd-` prefix are generated by Github automatically. They're just a copy of the repository tree, a la `git archive`.

The ones with the `libglvnd-` prefix are produced from a `make pkg` command, so the configure script and all the generated source files are included in it. Those have to be generated and added manually.

Anyway, if you need a consistent URL, then you'll want to get it from GitLab, which generates tarballs just like GitHub does.
