### ISSUE TITLE
testglxgetprocaddress is broken now

### ISSUE THREAD

**Issue by nwnk** [NVIDIA/libglvnd#32]
As of commit 11435a8cdb321393be3e952b8b4c3a95dae9cf22, `make check` no longer works on servers without x11glvnd (or possibly even with, I've not checked):
```
dmt:~/git/libglvnd% tests/testglxgetprocaddress
checking glXGetProcAddress
checking glXWaitGL
checking glXExampleExtensionFunction
Unexpected glXExampleExtensionFunction() return value!
```
I'm a little unsure whether this is a bug in the test or the implementation, but I'm leaning towards the former.  The test doesn't give libGL any information it could use to look up a vendor library.  I don't think it makes sense to force loading a vendor if `__GLX_VENDOR_LIBRARY_NAME` is set just to make this test work.  And applications relying on this kind of thing working are already a bit broken under Mesa.  We don't generate stubs for GLX entrypoints we don't know about, but just because we handed you the pointer doesn't mean it'll work if the driver doesn't support it.

I think we'd need to fix the test to do something to provoke libgl to actually load a vendor driver.

**Comment by kbrenneman** [comment]
Since glXGetProcAddress is supposed to be independent of any display, we should at least try to hand back any extension functions the app asks for, even if they're called before the first XOpenDisplay.

To be perfectly correct in all cases, it would need to load every vendor library from glXGetProcAddress, or at least load them until it finds one that offers the function that the app requested.

Alternately, glXGetProcAddress could just load the default library, now that we have one. That would probably give correct results in most cases, without the overhead of having to find and load every possible vendor library.

**Comment by kbrenneman** [comment]
Now that I look at the test itself, though, I'd agree that this failure is a bug in the test, not in libglvnd.

Unless a function is purely client-side, it would need a valid display and screen to know which library to dispatch to.

**Comment by kbrenneman** [comment]
Also note that the test will still need __GLX_VENDOR_LIBRARY_NAME to be set. Even if it doesn't need to pre-load the vendor library, it'll still need to override the vendor selection to force it to use the dummy vendor library.

**Comment by kbrenneman** [comment]
Okay, I've added an XOpenDisplay to fix the test itself.

I've opened issue #34 for the problem of calling glXGetProcAddress before a vendor library has been loaded.
