### ISSUE TITLE
Add an indirect rendering library

### ISSUE THREAD

**Issue by kbrenneman** [NVIDIA/libglvnd#39]
Using a fallback vendor for indirect rendering works for now, but a better long-term solution would be to add a dedicated indirect rendering library to libglvnd.

The indirect rendering library should use the same interface as a normal vendor library, but it would be independent of any hardware vendor library. libGLX would load and use the indirect rendering library the same way it uses a fallback vendor library now.

The first reason is that it removes the requirement to have another vendor library installed. In addition, it removes the need to add a symlink to another vendor library, which is the one remaining place where different installers or package managers would have to step on each other.

The second reason is that the indirect rendering library would serve as an example of how a vendor library works and how the ABI works. Developers could use it as a reference when building a hardware vendor library.

**Comment by nwnk** [comment]
This could also have the advantage that each vendor library need only implement enough GLX protocol for direct contexts (and whatever custom indirect GLX extensions it wants to support), and always use the indirect library for indirect contexts.

One question would be how to reflect this in CreateContext(direct==True), where currently you're allowed to get an indirect context. The choices are to ignore that possibility (and require the app ask for indirect explicitly), or have the loader fall back to indirect itself, or punt the decision to the vendor library.

**Comment by kbrenneman** [comment]
Good point, I hadn't thought of that.

If the app asks for direct rendering, then I guess there's still no harm in falling back to the indirect rendering library if the vendor library can't create a context. Any existing app that would want to make a decision based on whether or not it can get a direct rendering context would have to call glXIsDirect to find that out, so nothing would change from the app's perspective.

It would still need to deal with X errors, though, so that we don't have glXCreateContext both succeed and hit the app with an error.

Maybe the vendor library's MakeCurrent function could return a flag telling libGLX whether or not to try the indirect rendering library?

**Comment by nwnk** [comment]
Ugh, "direct" is a server choice isn't it. So CreateContext(direct=1) would need itself to call IsDirect (and let errors from the direct library bubble up to the caller, since the reply will flush them through), and if it returns false hand the created context to the indirect library a la ImportContextEXT.

I'm not totally sure my idea is so good.  If an indirect context ever finds itself in a vendor library (say because its the only one that implements glXHamSandwichEXT) then the lib is going to have a hard time _doing_ anything with that context unless the GLXContext struct used by the indirect library is exposed to vendors.  With just an opaque pointer the vendor lib won't even know how to look up the context tag or XID.  If we make it non-opaque we'd probably still need a "magic number at the head of the struct" convention so you know what to cast to, and even then we might need a way for the vendor libs to attach private data to the indirect context.

**Comment by kbrenneman** [comment]
A non-opaque GLXContext might be more complexity than it's worth. It would certainly make the ABI more complicated.

libGLX also has to deal with contexts that it didn't directly create, since it doesn't expose glXCreateContextAttribsARB. If there was some extra libGLX-specific data in a GLXContext handle, then we'd need to add a way for a vendor library to set those up.

**Comment by cubanismo** [comment]
While glXCreateContext(direct=yes) is certainly allowed to fall back to an indirect context, it's been pointed out to me before that more often than not, we might as well just fail in that case, since most apps really don't want indirect rendering.  I think it's only useful to fall back when we already knew up front that direct wasn't available (E.g., we couldn't find a local vendor library for that screen, or the vendor library immediately determined direct wasn't possible because we're on a different machine or similar situations), but I think in these most modern of times, it would be fine to fail context creation if we tried to create a direct context but failed for out of memory/hardware contexts/whatever resources.  That should avoid us needing to deal with the cases where X server errors are generated and simplify the client code needed to implement a fallback mechanism.

**Comment by kbrenneman** [comment]
For cases where libGLX knows in advance that direct rendering won't work, it could just override the vendor selection for the whole screen. For some cases, like when the server doesn't support x11glvnd, that's basically what it already does.

More generally, the vendor library could export a function which takes a display and screen number, and returns a flag telling libGLX whether it will be able to use that screen.

Then, if the vendor library says that it won't work on a particular X screen (whether because of indirect rendering support or anything else), then libGLX will fall back to using the indirect rendering library for that screen.

**Comment by cubanismo** [comment]
Yes, I like all of that.  That would mean you could just let CreateContext failure propagate up to the app in all cases, right?

**Comment by kbrenneman** [comment]
Right. If the vendor library says that it'll support a screen, then libGLX will let the vendor library handle it, including passing any errors or failures along to the app.

The only change would be when libGLX first selects a vendor library for the screen. After that, everything else is the same.

**Comment by kbrenneman** [comment]
We've migrated the repository over to GitLab, so this is now tracked at https://gitlab.freedesktop.org/glvnd/libglvnd/issues/39.
