### ISSUE TITLE
problem with libGLdispatch.so on grsecurity-enabled system

### ISSUE THREAD

**Issue by Marqin** [NVIDIA/libglvnd#53]
Hello,
I've got grsecurity enabled in my kernel and when I'm trying to run app that uses libGLdispatch.so I'm getting error
`kernel: grsec: denied RWX mprotect of /usr/lib/libGLdispatch.so.0`

Doing `readelf -edW /usr/lib/libGLdispatch.so.0` showed this:
`[10] wtext             PROGBITS        0000000000048000 048000 012000 00  AX  0   0 4096`
which looks supicious, because it has `w` in name ( like `writeable` ) but is not marked as writeable.

I see some people using Gentoo have the same [problem](https://archives.gentoo.org/gentoo-hardened/message/1cc6cd5e2c65b875cd926e08e0b9482e) with `libGLdispatch.so`. They also have some ideas about fixing it.

version: 358.16

**Comment by kbrenneman** [comment]
The TEXTREL marking in libGLdispatch.so is there because it uses absolute addresses in the x86-64 TSD stubs. We should have a fix for that in soon.

**Comment by kbrenneman** [comment]
Okay, I think Robert's fix should be sufficient.

@Marqin -- Can you double-check to make sure that this is fixed and we didn't miss anything?

**Comment by Marqin** [comment]
It's working :+1:

**Comment by kbrenneman** [comment]
Great, thanks.

**Comment by Marqin** [comment]
Do you maybe know if this fix will land in 364 driver pack or later? So I don't accidentaly overwrite this lib.

**Comment by kbrenneman** [comment]
I don't know what r364 will have, but if it uses libglvnd then it'll probably include this fix.

For what it's worth, though, barring any more ABI changes, it should be safe to use a locally-built copy of the libglvnd libraries instead of the ones from the nvidia installer package. The locally-build libraries will probably give better performance, too, since it can take advantage of features that the one from the installer can't.
