### ISSUE TITLE
TLS, TSD and pure C

### ISSUE THREAD

**Issue by evelikov** [NVIDIA/libglvnd#58]
After a discussion with Ian Romanick at FOSDEM, we've been leaning towards nuking the TSD code path for mesa. Obviously that's not an option for GLVND as some hunks are not functioning with TLS. So here are some related questions/suggestions:
- nuke the TSD path around as soon as TLS is up working :-)
- use consistent naming scheme for the symbols - _glapi_foo -> __glDispatchFoo
- hide the TLS/TSD symbols and use _glapi_get_current alone ? Not possible afaict :-(

How do the above sound ?
-Emil

**Comment by kbrenneman** [comment]
The TLS stubs are generally what you want to use whenever possible, but the TSD stubs still serve a couple of purposes.

The immediate problem, of course, is that that TLS stubs are still broken on x86, and they haven't been implemented for ARM yet.

Even once that's fixed, though, the TSD stubs are a useful fallback because they don't depend on any compiler extensions except for the inline assembly itself, and even that could probably be avoided if we needed to. Some sufficiently ancient compilers don't support the __thread keyword or the tls-exec attribute, which the TLS stubs rely on.

**Comment by evelikov** [comment]
Thinking about ancient compilers ... what is the scope of the project in terms of supporting them (libc, gcc, other versions would be appreciated).

I believe the idea is/was to have the distro ship GLVND, once everything is stabilised. In which case we can remove/ease some of the legacy code.

**Comment by kbrenneman** [comment]
I'd have to go digging to figure out exactly how far, but the NVIDIA driver at least supports systems that go back quite a long time.

**Comment by kbrenneman** [comment]
In any case, the TSD stubs don't impose much of a maintenance burden for now, so it's probably fine to keep them around as a fallback.

**Comment by evelikov** [comment]
> I believe the idea is/was to have the distro ship GLVND, once everything is stabilised. In which case we can remove/ease some of the legacy code

I believe you missed out the second part of my response (see above). Is this no longer the plan ?

**Comment by kbrenneman** [comment]
Having distros ship GLVND is the plan, but I expect it'll be quite a while before that's reliably the case.

By the time enough distros do include GLVND, then I hope the really ancient compilers will also be safe to ignore.

**Comment by mattst88** [comment]
I'd feel free to close this.
