### ISSUE TITLE
Version libGLdispatch.so ?

### ISSUE THREAD

**Issue by evelikov** [NVIDIA/libglvnd#59]
Inspired by another ticked/issue, I'm wondering if using a versioned SO will allow us to minimise issues as distributions/users misuse (read mix and match) the library and the rest of GLVND.

Unless we're planning to keep internal ABI/API as is - it's a bit hard to see into the future :-P

**Comment by kbrenneman** [comment]
The internal interface between libGLdispatch.so and libGLX.so is already versioned. GLdispatch.h defines GLDISPATCH_ABI_VERSION, and there's a __glDispatchGetABIVersion function to check the version number of libGLdispatch.so itself.

I don't expect it to be much of a problem in practice since it's an internal interface, but as you say, it's possible for someone to try to mix and match the libraries between versions.

The interface in GLdispatchABI.h is used by a vendor library, but that's better defined as part of the libGLX/libEGL interface. That is, if we change the interface in GLdispatchABI.h, we should bump the version number in libglxabi.h.

**Comment by evelikov** [comment]
I was thinking of the case where we remove/add symbols to the interface. In that case we might not even reach the constructor, as the symbol __glDispatchFoo is unresolved.

The benefit of the above is that it can be resolved/checked by standard distro packaging utilities. Then again I might be over-thinking/engineering it.

**Comment by kbrenneman** [comment]
If there's a version mismatch, there's not really anything the libraries can do except to call abort. If it runs into a missing symbol, then it'll do the same thing, and just terminate the process. The end result is the same.

Checking the version number at the beginning of _init in libGLX.so means that if there is a mismatch, then it'll fail early and loudly instead of crashing at some random point later on. That's probably the best that we can reasonably do.

**Comment by evelikov** [comment]
> The benefit of the above is that it can be resolved/checked by standard distro packaging utilities.

There is also the detail that everything that's shipped with the official proprietary drivers from NVIDIA, is versioned appropriately. Is libglapi.so.0 the inspiration to keep the version number as is ?

**Comment by kbrenneman** [comment]
The version number of zero is just because that's what we started with, we hadn't had any sort of a formal release yet, and the libGLdispatch.so interface changed quickly enough that bumping an ABI version for every change would have been impractical.

That said, libglapi.so.0 isn't a bad comparison. libGLdispatch.so is a purely internal detail like libglapi.so is. Vendor libraries don't talk to it directly, since everything goes through libGLX.so. Likewise, applications go through libGLX.so and (optionally) the entrypoint libraries.

The only requirement for the version of libGLdispatch.so is that it has to match the other libraries. The ABI version number is there as a quick sanity check for mismatched builds, but it doesn't have any use beyond that.

**Comment by evelikov** [comment]
Keeping the number to zero during development does make sense, although I would strongly suggest that we change that once things are stabilised. Why ?

- It allows us to check/test things before we run them. Not to mention that there are some cases where one simply cannot (is not allowed) execute it.
- libglapi.so.0 tries to battle some hysterical raisins - which can be avoided here. Namely the library was used by both xserver and mesa in a mix-and-match manner.
- your very own proprietary driver also uses explicit versioning. I'm sure that some of your colleagues can share more detailed reasons behind their choice.

Does any of these sound compelling enough ;-)

**Comment by aritger** [comment]
Emil: do you mean symbol versioning, or including the GLVND version string in the libGLdispatch.so SONAME?  I assume the latter.

Yes, from my point of view, and the reason we use it in the proprietary driver stack, is that including a version string in the SONAME lets a mismatch get caught by the loader (or maybe even distro tools, like you note).  I think doing that for any non-application-facing libraries within glvnd is a reasonable suggestion.

**Comment by evelikov** [comment]
@aritger you've got it spot on. All my bashing aside, I'm really glad that you guys added a runtime check.

**Comment by kbrenneman** [comment]
The version number that's in libGLdispatch.so is to check the (much more stable) interface between libGLdispatch.so and libGLX.so/libEGL.so.

The interface between libGLdispatch.so and the entrypoint libraries varies depending on the build configuration. A TLS-based build of libGL.so won't work with a TSD-based build of libGLdispatch.so, for example.

So, a simple revision number wouldn't be sufficient. But, maybe we could use a construct a version string from a version number (for the whole libglvnd package), plus the stub type and any other relevant configuration options.

**Comment by evelikov** [comment]
> The version number that's in libGLdispatch.so is to check the (much more stable) interface between libGLdispatch.so and libGLX.so/libEGL.so

And the SONAME one is to complement it without the runtime requirement. All the extra things that you're thinking about (as mentioned above) are not to be handled with a SONAME. That not how open-source projects work, I'm afraid.

@aritger can you please chip in and explain things from another angle. I feel like things are getting lost in translation somewhere along the line. Thanks !

**Comment by aritger** [comment]
Since Emil asked, I'll chime in, but I don't have much else to add: none of these checks are absolute, but I don't think they need to be.  They're hopefully easy to implement in libglvnd, and catch the majority of dumb configuration problems.

Once we start doing official libglvnd releases, and thus have a version number, I'd vote to append the version number to the libGLdispatch SONAME.

**Comment by kbrenneman** [comment]
To clarify: libGLdispatch.so does not have an ABI. It's strictly internal to libglvnd -- It doesn't talk to any driver or application. The fact that it even exists at all is an implementation detail.

Drivers (vendor libraries) talk to libGLX.so, through the interface defined in libglxabi.h. Applications talk to libGLX.so, and optionally to some combination of libOpenGL.so, libGL.so, libGLES\*.so, using the normal OpenGL and GLX functions.

libGLdispatch.so only talks to the other libglvnd libraries, so as long as they're all built from the same source tree and config options, everything's fine.

Any version check for libGLdispatch.so itself is not to provide any sort of compatibility. It's a rough, canary-in-the-coal mine sort of check for obviously broken installations.

**Comment by mattst88** [comment]
FWIW, I agree with Kyle. I don't see much if any point in adding a version to a completely internal library.

**Comment by kbrenneman** [comment]
Closing. If libGLdispatch.so ever gains an application- or driver-visible interface, or if library mismatches actually start being a problem, then we can look into adding a more comprehensive version number, but until then there's not much to gain from it.
