### ISSUE TITLE
pthreadFuncs vs c11/threads

### ISSUE THREAD

**Issue by evelikov** [NVIDIA/libglvnd#60]
Looking through the mesa/libglvnd discrepancies/evolution between the two and I'm wondering if it's worth removing the runtime resolution (a level of indirection) by using the c11/threads.h implementation from mesa.

The only downside I can see is that the rwlocks are missing from the standard. Then again looking at commit e4cdd1431b8 "GLX: Fix a couple deadlocks" makes me wonder if we have some metrics of the benefit of using rwlock vs normal mutex. IIRC the latter tends to be faster (implementation-wise) as well.

Can anyone share the reasoning (or numbers) behind the decision  ?

Thanks
Emil

**Comment by mattst88** [comment]
The purpose of c11/threads.h in Mesa is presumably that it provides an abstraction layer that allows Windows support. There's not much to be gained on Linux with C11 threads, since glibc doesn't offer an implementation.

pthreads is widely supported. C11 is not. I don't think platforms without pthreads are a concern for libglvnd (right?). So, just close this issue?

**Comment by kbrenneman** [comment]
I keep forgetting to come back and close this out, but that's correct. Windows support doesn't matter for libglvnd, so we can pretty much assume that pthreads will be available.

The use of rwlocks versus mutexes is still something of an open question until I can get some benchmarking data to compare, but that's orthogonal to this bug.
