### ISSUE TITLE
No reasonable way to clean up from some classes of errors

### ISSUE THREAD

**Issue by nwnk** [NVIDIA/libglvnd#88]
Consider this change to mesa's libglvnd branch, in particular the XXX bits:

https://cgit.freedesktop.org/mesa/mesa/commit/?h=libglvnd&id=f8208a6103d1beb69926e01230c86664f55c003a

It's a valid point! If adding the map fails we should destroy the context, but I don't see a sane way to do that. The obvious way would be `dd->staticDispatch.destroyContext(dpy, ctx)`, but that fails, because staticDispatch is opaque to the vendor library. __GLXapiExportsRec doesn't give you any way to look up a function other than by index, and there's no index for DestroyContext.

It doesn't work to call `glXGetProcAddress` for this, precisely because adding the map failed: the top-level dispatch for `glXDestroyContext` would have no idea which vendor to dispatch to, because the context wouldn't be recorded in the map. You have to dispatch directly back to the same vendor that just created the context.

**Comment by nwnk** [comment]
For similar reasons it doesn't work to call `glXDestroyContext` by name either. You might be able to make that bind to the entrypoint from glvnd, but it'd still fail at vendor lookup.

**Comment by kbrenneman** [comment]
What we'd need is a way to look up the vendor's glXDestroyContext.

One option would be to expand the GLX dispatch table so that you can look up glXDestroyContext using the same fetchDispatchEntry function. There might not be a good place to call setDispatchIndex for those functions, though.

A more direct option would be to look up a function by vendor and name, or at least add a way to get a dispatch index by name.

**Comment by kbrenneman** [comment]
We've migrated the repository over to GitLab, so this is now tracked at https://gitlab.freedesktop.org/glvnd/libglvnd/issues/88.
