### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by mlauss** [NVIDIA/libglvnd#94]
I'm trying to install a glvnd-enabled mesa alongside nvidia's binary blob.
It's working so far, but I have a couple of questions:

*) with glvnd enabled, mesa calls its libGL libGLX_mesa.  Should mesa's libEGL and libGLES* libs be similarly renamed (like the nvidia binary driver does) ?

*) Mesa installs gl.pc pkgconfig file, which instructs applications to link against libGLX_mesa. I suppose
that's wrong; however, what library SHOULD applications link against? libGL.so or libOpenGL.so?
Although it seems more logical that libglvnd provide these pkgconfig files (gl.pc, egl.pc, glesv1_cm.pc, glesv2.pc) in the future.

*) hows the egl vendor ICD system supposed to work?  I've put a minimal json for libEGL_nvidia.so at the appropriate place, I can see the library being opened, but eglInitialize always fails (running eglinfo under X).

Thanks!

**Comment by kbrenneman** [comment]
EGL support for libglvnd is still in progress. The changes for libglvnd itself are merged, and I sent a patch out for adding EGL support to Mesa a few days ago.

On the NVIDIA side, we should have a driver package with EGL support out pretty soon, but we haven't released one yet. What you'll find in the current packages is a thin wrapper around a normal driver, It doesn't deal with multiple vendor libraries, but it sets up the dispatch table so that libglvnd's libOpenGL.so and libGLES\*.so will work with it.

The libGLES\*.so libraries are part of libglvnd, and the functions that they export go through the normal. Those libraries will work with the current NVIDIA driver with both EGL and GLX. Under a libglvnd-enabled Mesa, they'll work with GLX, and they'll work with EGL once the patches for libglvnd-based EGL are checked in.

**Comment by kbrenneman** [comment]
> with glvnd enabled, mesa calls its libGL libGLX_mesa. Should mesa's libEGL and libGLES libs be similarly renamed (like the nvidia binary driver does) ?

In the NVIDIA driver, the libGLES*nvidia.so libraries are internal components, not things that applications should link against (or care about).

With Mesa, I think (but someone correct me if I'm wrong) the libGLES\*.so libraries are wrappers around Mesa's dispatch layer, so it should be safe to just replace those with libglvnd's libraries. Again, though, that's only the case once Mesa is updated to use libglvnd for EGL.

**Comment by kbrenneman** [comment]
> Mesa installs gl.pc pkgconfig file, which instructs applications to link against libGLX_mesa. I suppose that's wrong; however, what library SHOULD applications link against? libGL.so or libOpenGL.so?

Applications should link against libGL.so or libGLX.so.

libGL.so is a wrapper around libGLX.so, but from an application's perspective, it's the same as it would be for a non-libglvnd system. Use libGL.so if you want to maintain binary compatibility regardless of whether a system uses libglvnd or not.

On a libglvnd-based system, you can link against libGLX.so instead. It exports only GLX entrypoints, so to get OpenGL functions, you can optionally link against one of the entrypoint libraries, typically libOpenGL.so. It's optional because you could also just call eglGetProcAddress for everything.

On a libglvnd system, you can also link against libGLX.so, which only provides GLX entrypoints. Then, you can optionally link against libOpenGL.so or any of the libGLES\*.so libraries.

Note that the GL entrypoints all go through the same dispatch table, so the same function is interchangeable no matter where you look it up -- libOpenGL.so, libGL.so, libGLES\*.so, glXGetProcAddress, and eglGetProcAddress.

**Comment by mlauss** [comment]
Thank you for your answers!

I should have read the other threads first, some of the mesa developers already asked the same
questions I did (among others, where's the official Khronos GL Header repo for instance).

Thanks for your efforts!  What's in this repo already works very well (with mesa too!)
